### ISSUE TITLE
B_y label not showing in plot?

### ISSUE THREAD

**Issue by edmondb** [heliohackweek/mms_data_hunt#4]
Just noticed this...not sure if it was cut out from the display or what?

https://github.com/heliohackweek/mms_data_hunt/blob/master/memes/example_sitl_read.ipynb#L10

![image](https://user-images.githubusercontent.com/1493949/91300163-cffc6700-e770-11ea-843d-515e3c456e02.png)

**Comment by bairaelyn** [comment]
Fixed with 57a751b95fc280309b40bb2ca28a27c3de3c944f.
